name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: windows-2022
            platform: windows
            arch: x64
          - os: macos-13
            platform: macos
            arch: x64
          - os: macos-14
            platform: macos
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: ffi
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Build PHAR
        run: |
          echo "Building on ${{ runner.os }} (${{ matrix.arch }})..."
          php toolkit app:build tools --timeout=600

      - name: Set binary name
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            echo "BINARY_NAME=tools-linux" >> $GITHUB_ENV
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "BINARY_NAME=tools-windows.exe" >> $GITHUB_ENV
          elif [[ "${{ runner.os }}" == "macOS" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "BINARY_NAME=tools-macos-arm64" >> $GITHUB_ENV
          elif [[ "${{ runner.os }}" == "macOS" && "${{ matrix.arch }}" == "x64" ]]; then
            echo "BINARY_NAME=tools-macos-x64" >> $GITHUB_ENV
          fi

      - name: Rename binary
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ren builds\tools.exe builds\${{ env.BINARY_NAME }}
          else
            mv builds/tools builds/${{ env.BINARY_NAME }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tools-${{ matrix.platform }}-${{ matrix.arch }}
          path: builds/${{ env.BINARY_NAME }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          find . -type f -name "tools-*" | sort

      - name: Get version from tag
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=untagged-$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          artifacts: "tools-linux-x64/tools-linux,tools-windows-x64/tools-windows.exe,tools-macos-arm64/tools-macos-arm64,tools-macos-x64/tools-macos-x64"
          artifactErrorsFailBuild: true
          allowUpdates: true